// --------------- AUTH ------------------ //
export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const UPDATE_PASSWORD = 'update_password';
export const UPDATE_PASSWORD_SUCCESS = 'update_password_success';
export const UPDATE_PASSWORD_FAIL = 'update_password_fail';
export const PASSWORD_MISMATCH = 'password_mismatch';
export const REGISTER_TOGGLE = 'register_toggle';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const SIGNUP_USER_SUCCESS = 'signup_user_success';
export const SIGNUP_USER_FAIL = 'sign_up_user_fail';
export const LOGOUT = 'user_logout';
export const AUTHENTICATE_CURRENT_USER = 'authenticate_current_user';
export const LOAD_FORGOT_PASSWORD_SCREEN = 'load_forgot_password_screen';
export const SEND_PASSWORD_RESET_EMAIL = 'send_password_reset_email';
export const SEND_PASSWORD_RESET_EMAIL_FAIL = 'send_password_reset_email_fail';
