export * from './ChangeCurrency';
export * from './ChangePassword';
export * from './Feedback';
export * from './PrivacyTerms';
export * from './ReturnPolicy';
export * from './ShippingInfo';
export * from './About';
export * from './Settings';
export * from './EditProfile';
